# Generated by Django 4.2.5 on 2023-09-13 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('value', models.CharField(max_length=250)),
                ('Type', models.CharField(max_length=250)),
                ('Active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'G.  Master Data',
            },
        ),
    ]
