# Generated by Django 4.2.5 on 2023-09-21 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Settings', '0002_masterdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='Active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='Active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='state',
            name='Active',
            field=models.BooleanField(default=True),
        ),
    ]
