# Generated by Django 4.2.5 on 2023-09-13 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Settings', '0002_masterdata'),
        ('Student', '0002_remove_studentform_payment_mode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receipt',
            options={'verbose_name_plural': 'C.Receipts'},
        ),
        migrations.AlterModelOptions(
            name='studentform',
            options={'verbose_name_plural': 'A.Student Forms'},
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fee_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Settings.masterdata')),
                ('student_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.studentform')),
            ],
            options={
                'verbose_name_plural': 'B.Fee_type',
            },
        ),
    ]
