# Generated by Django 4.2.5 on 2023-09-22 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0010_remove_receipt_student_form_delete_payment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentform',
            name='feestype',
        ),
        migrations.AddField(
            model_name='studentform',
            name='payment_type',
            field=models.CharField(choices=[('full_payment', 'Full Payment'), ('instalment_payment', 'Instalment Payment')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
