# Generated by Django 4.2.5 on 2023-09-22 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Settings', '0004_rename_type_masterdata_type'),
        ('Student', '0011_remove_studentform_feestype_studentform_payment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentform',
            name='payment_type',
        ),
        migrations.AddField(
            model_name='studentform',
            name='feestype',
            field=models.ForeignKey(choices=[('one time', 'One Time '), ('2time', 'Two Time ')], default=1, limit_choices_to={'type': 'Fee Type'}, on_delete=django.db.models.deletion.CASCADE, related_name='FeeStudents', to='Settings.masterdata', verbose_name='Installment Type'),
            preserve_default=False,
        ),
    ]
