# Generated by Django 4.2.5 on 2023-09-22 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0015_alter_studentform_feestype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentform',
            name='feestype',
        ),
        migrations.AlterField(
            model_name='studentform',
            name='payment_type',
            field=models.CharField(choices=[('One Time', 'One Time '), ('Two Time', 'Two Time ')], max_length=20, verbose_name='Installment Type'),
        ),
    ]
