# Generated by Django 4.2.5 on 2023-09-24 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0016_remove_studentform_feestype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=100)),
                ('student_form', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Student.studentform')),
            ],
        ),
    ]
