# Generated by Django 4.2.5 on 2023-09-25 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0017_receipts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('studentform_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Student.studentform')),
                ('receipt_number', models.CharField(max_length=100)),
            ],
            bases=('Student.studentform',),
        ),
        migrations.DeleteModel(
            name='Receipts',
        ),
    ]
