# Generated by Django 4.2.5 on 2023-09-25 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0018_receipt_delete_receipts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipts',
            fields=[
                ('receipt_number', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('payment_type', models.CharField(max_length=20, verbose_name='Installment Type')),
                ('student_form', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Student.studentform')),
            ],
        ),
        migrations.DeleteModel(
            name='Receipt',
        ),
    ]
