# Generated by Django 4.2.5 on 2023-09-25 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0019_receipts_delete_receipt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipts',
            name='payment_type',
        ),
        migrations.AddField(
            model_name='receipts',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='receipts',
            name='receipt_number',
            field=models.CharField(max_length=100),
        ),
    ]
