# Generated by Django 4.2.5 on 2023-09-25 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0020_remove_receipts_payment_type_receipts_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipts',
            name='id',
        ),
        migrations.AlterField(
            model_name='receipts',
            name='receipt_number',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
