# Generated by Django 4.2.5 on 2023-09-26 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0023_alter_receipts_student_form'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipts',
            old_name='receipt_number',
            new_name='amount',
        ),
    ]
