# Generated by Django 4.2.5 on 2023-09-26 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0024_rename_receipt_number_receipts_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipts',
            old_name='amount',
            new_name='receipt_number',
        ),
    ]
