# Generated by Django 4.2.5 on 2023-09-26 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0025_rename_amount_receipts_receipt_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipts',
            old_name='receipt_number',
            new_name='amount',
        ),
    ]
