# Generated by Django 4.2.5 on 2023-09-26 17:47

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('Settings', '0005_rename_state_district_state_rename_state_state_state_and_more'),
        ('Student', '0027_alter_studentform_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentform',
            name='district',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='state', chained_model_field='state', on_delete=django.db.models.deletion.CASCADE, to='Settings.district'),
        ),
    ]
